/*
 * Copyright 2020 Kaiserpfalz EDV-Service, Roland T. Lichti.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstalledFeatures) DeepCopyInto(out *InstalledFeatures) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstalledFeatures.
func (in *InstalledFeatures) DeepCopy() *InstalledFeatures {
	if in == nil {
		return nil
	}
	out := new(InstalledFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstalledFeatures) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstalledFeaturesDependency) DeepCopyInto(out *InstalledFeaturesDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstalledFeaturesDependency.
func (in *InstalledFeaturesDependency) DeepCopy() *InstalledFeaturesDependency {
	if in == nil {
		return nil
	}
	out := new(InstalledFeaturesDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstalledFeaturesList) DeepCopyInto(out *InstalledFeaturesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstalledFeatures, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstalledFeaturesList.
func (in *InstalledFeaturesList) DeepCopy() *InstalledFeaturesList {
	if in == nil {
		return nil
	}
	out := new(InstalledFeaturesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstalledFeaturesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstalledFeaturesSpec) DeepCopyInto(out *InstalledFeaturesSpec) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]InstalledFeaturesDependency, len(*in))
		copy(*out, *in)
	}
	if in.Conflicts != nil {
		in, out := &in.Conflicts, &out.Conflicts
		*out = make([]InstalledFeaturesDependency, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstalledFeaturesSpec.
func (in *InstalledFeaturesSpec) DeepCopy() *InstalledFeaturesSpec {
	if in == nil {
		return nil
	}
	out := new(InstalledFeaturesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstalledFeaturesStatus) DeepCopyInto(out *InstalledFeaturesStatus) {
	*out = *in
	out.Feature = in.Feature
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstalledFeaturesStatus.
func (in *InstalledFeaturesStatus) DeepCopy() *InstalledFeaturesStatus {
	if in == nil {
		return nil
	}
	out := new(InstalledFeaturesStatus)
	in.DeepCopyInto(out)
	return out
}
